In [4]:
import pandas as pd

# Ruta al archivo CSV en Kaggle
file_path = '/kaggle/input/proyectonc/data_latinoamerica.csv'

# Cargar el archivo CSV con pandas
df = pd.read_csv(file_path)

# Visualizar las primeras 10 filas
df.head(10)

,location_key,date,country_code,country_name,new_confirmed,new_deceased,cumulative_confirmed,cumulative_deceased,cumulative_vaccine_doses_administered,population,...,population_largest_city,area_rural_sq_km,area_urban_sq_km,life_expectancy,adult_male_mortality_rate,adult_female_mortality_rate,pollution_mortality_rate,comorbidity_mortality_rate,new_recovered,cumulative_recovered
0,AR,2020-01-01,AR,Argentina,3.0,0.0,3.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
1,AR,2020-01-02,AR,Argentina,14.0,0.0,17.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
2,AR,2020-01-03,AR,Argentina,3.0,0.0,20.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
3,AR,2020-01-04,AR,Argentina,7.0,0.0,27.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
4,AR,2020-01-05,AR,Argentina,5.0,0.0,32.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
5,AR,2020-01-06,AR,Argentina,9.0,0.0,41.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
6,AR,2020-01-07,AR,Argentina,4.0,0.0,45.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
7,AR,2020-01-08,AR,Argentina,3.0,0.0,48.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
8,AR,2020-01-09,AR,Argentina,0.0,0.0,48.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
9,AR,2020-01-10,AR,Argentina,1.0,0.0,49.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN

In [5]:
# Seleccionar las columnas 20 a 28
columns_20_to_28 = df.iloc[:, 20:28]

# Mostrar las columnas seleccionadas
print(columns_20_to_28)

          population_age_40_49  population_age_50_59  population_age_60_69  \
0                    4507125.0             3911943.0             2914251.0
1                    4507125.0             3911943.0             2914251.0
2                    4507125.0             3911943.0             2914251.0
3                    4507125.0             3911943.0             2914251.0
4                    4507125.0             3911943.0             2914251.0
...                        ...                   ...                   ...
12216052               18172.0               12413.0                7009.0
12216053               18172.0               12413.0                7009.0
12216054               18172.0               12413.0                7009.0
12216055               18172.0               12413.0                7009.0
12216056               18172.0               12413.0                7009.0

          population_age_70_79  population_age_80_and_older       gdp_usd  \
0                    1817557.0                     994030.0  4.496634e+11
1                    1817557.0                     994030.0  4.496634e+11
2                    1817557.0                     994030.0  4.496634e+11
3                    1817557.0                     994030.0  4.496634e+11
4                    1817557.0                     994030.0  4.496634e+11
...                        ...                          ...           ...
12216052                3095.0                       1094.0           NaN
12216053                3095.0                       1094.0           NaN
12216054                3095.0                       1094.0           NaN
12216055                3095.0                       1094.0           NaN
12216056                3095.0                       1094.0           NaN

          gdp_per_capita_usd  latitude
0                    10006.0     -34.0
1                    10006.0     -34.0
2                    10006.0     -34.0
3                    10006.0     -34.0
4                    10006.0     -34.0
...                      ...       ...
12216052                 NaN       3.5
12216053                 NaN       3.5
12216054                 NaN       3.5
12216055                 NaN       3.5
12216056                 NaN       3.5

[12216057 rows x 8 columns]

In [7]:
# Verificar si hay valores nulos en las columnas seleccionadas
null_counts = columns_20_to_28.isnull().sum()

# Mostrar el conteo de valores nulos por columna
print("Conteo de valores nulos por columna:")
print(null_counts)

# Verificar si hay valores nulos en alguna de las columnas
if null_counts.any():
    print("\nHay valores nulos en las columnas seleccionadas.")
else:
    print("\nNo hay valores nulos en las columnas seleccionadas.")

Conteo de valores nulos por columna:
population_age_40_49            1466680
population_age_50_59            1466680
population_age_60_69            1466680
population_age_70_79            1466680
population_age_80_and_older     1466680
gdp_usd                        12196237
gdp_per_capita_usd             12195246
latitude                         422166
dtype: int64

Hay valores nulos en las columnas seleccionadas.

In [10]:
# Imputación por valor constante (ejemplo: reemplazar NaN con 0)
df_filled = df.fillna(value=0)

# Mostrar las primeras filas del DataFrame después de la imputación
print(df_filled.head())

  location_key        date country_code country_name  new_confirmed  \
0           AR  2020-01-01           AR    Argentina            3.0
1           AR  2020-01-02           AR    Argentina           14.0
2           AR  2020-01-03           AR    Argentina            3.0
3           AR  2020-01-04           AR    Argentina            7.0
4           AR  2020-01-05           AR    Argentina            5.0

   new_deceased  cumulative_confirmed  cumulative_deceased  \
0           0.0                   3.0                  0.0
1           0.0                  17.0                  0.0
2           0.0                  20.0                  0.0
3           0.0                  27.0                  0.0
4           0.0                  32.0                  0.0

   cumulative_vaccine_doses_administered  population  ...  \
0                                    0.0  44938712.0  ...
1                                    0.0  44938712.0  ...
2                                    0.0  44938712.0  ...
3                                    0.0  44938712.0  ...
4                                    0.0  44938712.0  ...

   population_largest_city  area_rural_sq_km  area_urban_sq_km  \
0               15057273.0         2690269.0           55032.0
1               15057273.0         2690269.0           55032.0
2               15057273.0         2690269.0           55032.0
3               15057273.0         2690269.0           55032.0
4               15057273.0         2690269.0           55032.0

   life_expectancy  adult_male_mortality_rate  adult_female_mortality_rate  \
0            76.52                    147.086                       79.483
1            76.52                    147.086                       79.483
2            76.52                    147.086                       79.483
3            76.52                    147.086                       79.483
4            76.52                    147.086                       79.483

   pollution_mortality_rate  comorbidity_mortality_rate  new_recovered  \
0                      26.6                        15.8            0.0
1                      26.6                        15.8            0.0
2                      26.6                        15.8            0.0
3                      26.6                        15.8            0.0
4                      26.6                        15.8            0.0

   cumulative_recovered
0                   0.0
1                   0.0
2                   0.0
3                   0.0
4                   0.0

[5 rows x 50 columns]

In [11]:
# Mostrar las primeras filas del DataFrame después de la imputación
print(df_filled.head())

  location_key        date country_code country_name  new_confirmed  \
0           AR  2020-01-01           AR    Argentina            3.0
1           AR  2020-01-02           AR    Argentina           14.0
2           AR  2020-01-03           AR    Argentina            3.0
3           AR  2020-01-04           AR    Argentina            7.0
4           AR  2020-01-05           AR    Argentina            5.0

   new_deceased  cumulative_confirmed  cumulative_deceased  \
0           0.0                   3.0                  0.0
1           0.0                  17.0                  0.0
2           0.0                  20.0                  0.0
3           0.0                  27.0                  0.0
4           0.0                  32.0                  0.0

   cumulative_vaccine_doses_administered  population  ...  \
0                                    0.0  44938712.0  ...
1                                    0.0  44938712.0  ...
2                                    0.0  44938712.0  ...
3                                    0.0  44938712.0  ...
4                                    0.0  44938712.0  ...

   population_largest_city  area_rural_sq_km  area_urban_sq_km  \
0               15057273.0         2690269.0           55032.0
1               15057273.0         2690269.0           55032.0
2               15057273.0         2690269.0           55032.0
3               15057273.0         2690269.0           55032.0
4               15057273.0         2690269.0           55032.0

   life_expectancy  adult_male_mortality_rate  adult_female_mortality_rate  \
0            76.52                    147.086                       79.483
1            76.52                    147.086                       79.483
2            76.52                    147.086                       79.483
3            76.52                    147.086                       79.483
4            76.52                    147.086                       79.483

   pollution_mortality_rate  comorbidity_mortality_rate  new_recovered  \
0                      26.6                        15.8            0.0
1                      26.6                        15.8            0.0
2                      26.6                        15.8            0.0
3                      26.6                        15.8            0.0
4                      26.6                        15.8            0.0

   cumulative_recovered
0                   0.0
1                   0.0
2                   0.0
3                   0.0
4                   0.0

[5 rows x 50 columns]